sudo: required

services:
    - docker

before_install:
    - docker build -t greek96/docker-travis-react -f Dockerfile.dev .

script:
    - docker run -e CI=true greek96/docker-travis-react yarn test